---
# Nginxサーバー設定プレイブック
# 実行例: ansible-playbook playbooks/nginx.yaml

- name: Apply common configuration to Nginx servers
  hosts: nginx
  become: yes
  tags:
    - common
  
  roles:
    - common

- name: Setup Nginx server
  hosts: nginx
  become: yes
  tags:
    - nginx
  
  roles:
    - nginx
